dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
